Add asm detection back to ./configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -140,6 +140,28 @@ cxx_check() {
     return $res
 }
 
+as_check() {
+    log_check "whether $AS supports $1"
+    echo "$1" > conftest.asm
+    if $AS conftest.asm $ASFLAGS $2 -o conftest.o >conftest.log 2>&1; then
+        res=$?
+        log_ok
+    else
+        res=$?
+        log_fail
+        log_msg "Failed commandline was:"
+        log_msg "--------------------------------------------------"
+        log_msg "$AS conftest.asm $ASFLAGS $2 -o conftest.o"
+        cat conftest.log >> config.log
+        log_msg "--------------------------------------------------"
+        log_msg "Failed program was:"
+        log_msg "--------------------------------------------------"
+        cat conftest.asm >> config.log
+        log_msg "--------------------------------------------------"
+    fi
+    return $res
+}
+
 define() {
     echo "#define $1$([ -n "$2" ] && echo " $2" || echo " 1")" >> config.h
 }
@@ -159,6 +181,7 @@ libdir='${exec_prefix}/lib'
 includedir='${prefix}/include'
 DEVNULL='/dev/null'
 
+asm="auto"
 debug="no"
 libx264="auto"
 lmpegts="auto"
@@ -442,6 +465,28 @@ elif cc_check '' -std=c99 ; then
     CFLAGS="$CFLAGS -std=c99 -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE"
 fi
 
+if [ $asm = auto -a \( $ARCH = X86 -o $ARCH = X86_64 \) ] ; then
+    if ! as_check "vpaddw xmm0, xmm0, xmm0" ; then
+        VER=`($AS --version || echo no assembler) 2>/dev/null | head -n 1`
+        echo "Found $VER"
+        echo "Minimum version is yasm-0.7.0"
+        echo "If you really want to compile without asm, configure with --disable-asm."
+        exit 1
+    fi
+    if ! cc_check '' '' '__asm__("pabsw %xmm0, %xmm0");' ; then
+        VER=`(${cross_prefix}as --version || echo no gnu as) 2>/dev/null | head -n 1`
+        echo "Found $VER"
+        echo "Minimum version is binutils-2.17"
+        echo "Your compiler can't handle inline SSSE3 asm."
+        echo "If you really want to compile without asm, configure with --disable-asm."
+        exit 1
+    fi
+    define HAVE_MMX
+fi
+
+[ $asm = no ] && AS=""
+[ "x$AS" = x ] && asm="no" || asm="yes"
+
 define ARCH_$ARCH
 define SYS_$SYS
 
@@ -640,6 +685,13 @@ if [ "$lzvbi" = "yes" ] ; then
     LDFLAGS="$LDFLAGS $LZVBI_LIBS"
 fi
 
+if [ "$pic" = "yes" ] ; then
+    CFLAGS="$CFLAGS -fPIC"
+    ASFLAGS="$ASFLAGS -DPIC"
+    # resolve textrels in the x86 asm
+    cc_check stdio.h -Wl,-Bsymbolic && LDFLAGS="$LDFLAGS -Wl,-Bsymbolic"
+fi
+
 if [ "$debug" != "yes" ]; then
     CFLAGS="$CFLAGS -s -fomit-frame-pointer"
     LDFLAGS="$LDFLAGS -s"
@@ -710,6 +762,7 @@ System Information
 
 Platform:   $ARCH
 System:     $SYS
+asm:        $asm
 
 Input
 
